spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=rm554327
spring.datasource.password=020604
app.oracle.default-schema=RM554327
spring.profiles.active=local
server.port=8082
